/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as AppExercisesRouteImport } from './routes/_app.exercises'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRankingsRouteImport } from './routes/_app.rankings'
import { Route as AppSessionRouteImport } from './routes/_app.session'
import { Route as AppTrainRouteImport } from './routes/_app.train'
import { Route as AppExercisesSlugRouteImport } from './routes/_app.exercises_.$slug'
import { Route as AppRoutinesIdRouteImport } from './routes/_app.routines.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainRoute = AppTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesSlugRoute = AppExercisesSlugRouteImport.update({
  id: '/exercises_/$slug',
  path: '/exercises/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesIdRoute = AppRoutinesIdRouteImport.update({
  id: '/routines/$id',
  path: '/routines/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/coach': typeof AppCoachRoute
  '/exercises': typeof AppExercisesRoute
  '/profile': typeof AppProfileRoute
  '/rankings': typeof AppRankingsRoute
  '/session': typeof AppSessionRoute
  '/train': typeof AppTrainRoute
  '/exercises/$slug': typeof AppExercisesSlugRoute
  '/routines/$id': typeof AppRoutinesIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/coach': typeof AppCoachRoute
  '/exercises': typeof AppExercisesRoute
  '/profile': typeof AppProfileRoute
  '/rankings': typeof AppRankingsRoute
  '/session': typeof AppSessionRoute
  '/train': typeof AppTrainRoute
  '/': typeof AppIndexRoute
  '/exercises/$slug': typeof AppExercisesSlugRoute
  '/routines/$id': typeof AppRoutinesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/exercises': typeof AppExercisesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/rankings': typeof AppRankingsRoute
  '/_app/session': typeof AppSessionRoute
  '/_app/train': typeof AppTrainRoute
  '/_app/': typeof AppIndexRoute
  '/_app/exercises_/$slug': typeof AppExercisesSlugRoute
  '/_app/routines/$id': typeof AppRoutinesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/coach'
    | '/exercises'
    | '/profile'
    | '/rankings'
    | '/session'
    | '/train'
    | '/exercises/$slug'
    | '/routines/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/coach'
    | '/exercises'
    | '/profile'
    | '/rankings'
    | '/session'
    | '/train'
    | '/'
    | '/exercises/$slug'
    | '/routines/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/coach'
    | '/_app/exercises'
    | '/_app/profile'
    | '/_app/rankings'
    | '/_app/session'
    | '/_app/train'
    | '/_app/'
    | '/_app/exercises_/$slug'
    | '/_app/routines/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rankings': {
      id: '/_app/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session': {
      id: '/_app/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/train': {
      id: '/_app/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof AppTrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises_/$slug': {
      id: '/_app/exercises_/$slug'
      path: '/exercises/$slug'
      fullPath: '/exercises/$slug'
      preLoaderRoute: typeof AppExercisesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines/$id': {
      id: '/_app/routines/$id'
      path: '/routines/$id'
      fullPath: '/routines/$id'
      preLoaderRoute: typeof AppRoutinesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppExercisesRoute: typeof AppExercisesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRankingsRoute: typeof AppRankingsRoute
  AppSessionRoute: typeof AppSessionRoute
  AppTrainRoute: typeof AppTrainRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExercisesSlugRoute: typeof AppExercisesSlugRoute
  AppRoutinesIdRoute: typeof AppRoutinesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppExercisesRoute: AppExercisesRoute,
  AppProfileRoute: AppProfileRoute,
  AppRankingsRoute: AppRankingsRoute,
  AppSessionRoute: AppSessionRoute,
  AppTrainRoute: AppTrainRoute,
  AppIndexRoute: AppIndexRoute,
  AppExercisesSlugRoute: AppExercisesSlugRoute,
  AppRoutinesIdRoute: AppRoutinesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
