/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCatalogRouteImport } from './routes/_app.catalog'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppRankingsRouteImport } from './routes/_app.rankings'
import { Route as AppSessionRouteImport } from './routes/_app.session'
import { Route as AppTrainRouteImport } from './routes/_app.train'
import { Route as AppCatalogSlugRouteImport } from './routes/_app.catalog_.$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainRoute = AppTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogSlugRoute = AppCatalogSlugRouteImport.update({
  id: '/catalog_/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/catalog': typeof AppCatalogRoute
  '/coach': typeof AppCoachRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/rankings': typeof AppRankingsRoute
  '/session': typeof AppSessionRoute
  '/train': typeof AppTrainRoute
  '/catalog/$slug': typeof AppCatalogSlugRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/catalog': typeof AppCatalogRoute
  '/coach': typeof AppCoachRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/rankings': typeof AppRankingsRoute
  '/session': typeof AppSessionRoute
  '/train': typeof AppTrainRoute
  '/': typeof AppIndexRoute
  '/catalog/$slug': typeof AppCatalogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/catalog': typeof AppCatalogRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/rankings': typeof AppRankingsRoute
  '/_app/session': typeof AppSessionRoute
  '/_app/train': typeof AppTrainRoute
  '/_app/': typeof AppIndexRoute
  '/_app/catalog_/$slug': typeof AppCatalogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/catalog'
    | '/coach'
    | '/profile'
    | '/progress'
    | '/rankings'
    | '/session'
    | '/train'
    | '/catalog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/catalog'
    | '/coach'
    | '/profile'
    | '/progress'
    | '/rankings'
    | '/session'
    | '/train'
    | '/'
    | '/catalog/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/catalog'
    | '/_app/coach'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/rankings'
    | '/_app/session'
    | '/_app/train'
    | '/_app/'
    | '/_app/catalog_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog': {
      id: '/_app/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rankings': {
      id: '/_app/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session': {
      id: '/_app/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/train': {
      id: '/_app/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof AppTrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog_/$slug': {
      id: '/_app/catalog_/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof AppCatalogSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCatalogRoute: typeof AppCatalogRoute
  AppCoachRoute: typeof AppCoachRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppRankingsRoute: typeof AppRankingsRoute
  AppSessionRoute: typeof AppSessionRoute
  AppTrainRoute: typeof AppTrainRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCatalogSlugRoute: typeof AppCatalogSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatalogRoute: AppCatalogRoute,
  AppCoachRoute: AppCoachRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppRankingsRoute: AppRankingsRoute,
  AppSessionRoute: AppSessionRoute,
  AppTrainRoute: AppTrainRoute,
  AppIndexRoute: AppIndexRoute,
  AppCatalogSlugRoute: AppCatalogSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
